trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Installe Node.js"

  - script: npm install
    displayName: "Installe les dépendances"

  - script: npx playwright install --with-deps
    displayName: "Installe les navigateurs Playwright"

  - script: npx playwright test
    displayName: "Lance les tests Playwright"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "test-results/*.xml"
    displayName: "Publie les résultats"

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: "playwright-report"
      artifact: "playwright-report"
    displayName: "Publie le rapport HTML"
